# configs/ppo_agent/actor_config_efficient.yaml
# Efficient actor for fast inference
layer_sizes: [128, 64]
activation: relu  # Fast activation
use_layer_norm: false
use_batch_norm: false
use_spectral_norm: false
dropout_rate: 0.0
initialization: kaiming
gain: 1.0