# configs/ppo_agent/critic_config_large.yaml
# Large critic network for complex environments
layer_sizes: [256, 256]
activation: relu
use_layer_norm: true
use_batch_norm: false
use_spectral_norm: false
dropout_rate: 0.0
initialization: orthogonal
gain: 1.0
