# ----------------------------------------
# actor_network_config.yaml
# ----------------------------------------
# Actor network architecture configuration
network_type: "mlp"
hidden_sizes: [256, 256]
activation: "tanh"
use_layer_norm: false
dropout_rate: 0.0

# Initialization
init_method: "orthogonal"
init_gain: 0.01  # Small for stable initial policy

# Architecture variants
use_lstm: false
lstm_hidden_size: 128
use_attention: false
attention_heads: 4
