# ----------------------------------------
# critic_network_config.yaml
# ----------------------------------------
# Critic network architecture configuration
network_type: "mlp"
hidden_sizes: [256, 256]
activation: "tanh"
use_layer_norm: false
dropout_rate: 0.0

# Initialization
init_method: "orthogonal"
init_gain: 1.0  # Standard for value function

# Architecture variants
use_lstm: false
lstm_hidden_size: 128
use_attention: false
attention_heads: 4
separate_networks: true  # Separate actor-critic networks
